apiVersion: v1
kind: Namespace
metadata:
  name: fileservice
  labels:
    name: fileservice
    app: fileservice
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fileservice-limit-range
  namespace: fileservice
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container