global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Permission Service metrics
  - job_name: 'permission-service'
    static_configs:
      - targets: ['permission-service:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # gRPC metrics
  - job_name: 'permission-service-grpc'
    static_configs:
      - targets: ['permission-service:50051']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s