apiVersion: v1
kind: Namespace
metadata:
  name: webbff
  labels:
    name: webbff
    app: webbff
---
apiVersion: v1
kind: LimitRange
metadata:
  name: webbff-limit-range
  namespace: webbff
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container