# PyAirtable Plugin Service Configuration
# This file contains the default configuration for the plugin service
# Environment variables with PLUGIN_SERVICE_ prefix will override these values

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

database:
  host: "localhost"
  port: 5432
  user: "plugin_service"
  password: "plugin_password"
  dbname: "plugin_service"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
  migrations_path: "./migrations"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  idle_timeout: 5m

runtime:
  engine: "wazero"  # wazero or wasmtime
  max_instances: 100
  instance_timeout: 30s
  cache_size: 50
  precompile_plugins: true
  
  # Default resource limits for plugins
  default_limits:
    max_memory_mb: 64
    max_cpu_percent: 50
    max_execution_ms: 5000
    max_storage_mb: 10
    max_network_reqs: 10
  
  # Maximum allowed resource limits
  max_limits:
    max_memory_mb: 256
    max_cpu_percent: 100
    max_execution_ms: 30000
    max_storage_mb: 100
    max_network_reqs: 100

security:
  jwt_secret: "change-me-in-production"
  jwt_expiration_time: 1h
  code_signing_enabled: true
  trusted_signers: []
  sandbox_enabled: true
  permission_check_enabled: true
  max_plugin_size: 10485760  # 10MB
  allowed_file_types: ["wasm", "wat"]
  quarantine_enabled: true
  quarantine_time: 24h

registry:
  default_registry: "official"
  official_registry: "https://plugins.pyairtable.com"
  cache_enabled: true
  cache_ttl: 1h
  sync_interval: 24h
  registries: []

monitoring:
  enabled: true
  metrics_enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  tracing_enabled: false
  tracing_endpoint: ""
  service_name: "plugin-service"
  log_level: "info"
  audit_log_enabled: true
  metrics_interval: 15s

storage:
  type: "local"  # local, s3, gcs, azure
  local:
    base_path: "./data/plugins"
    permissions: 0755
  s3:
    bucket: ""
    region: ""
    access_key_id: ""
    secret_access_key: ""
    endpoint: ""
    use_ssl: true
    path_style: false
  max_file_size: 52428800  # 50MB
  temp_dir: "/tmp/plugin-service"
  encryption:
    enabled: false
    key: ""
    algorithm: "AES-256-GCM"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file, both  
  file_path: "/var/log/plugin-service.log"
  max_size: 100  # megabytes
  max_backups: 3
  max_age: 28  # days
  compress: true

# Development-specific settings
development:
  enabled: false
  mock_external_apis: false
  debug_mode: false
  hot_reload: false