apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: apigateway

namespace: apigateway

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: apigateway
  newTag: latest

commonLabels:
  app: apigateway
  environment: production

patches:
- target:
    kind: Deployment
    name: apigateway
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3