apiVersion: v1
kind: Namespace
metadata:
  name: apigateway
  labels:
    name: apigateway
    app: apigateway
---
apiVersion: v1
kind: LimitRange
metadata:
  name: apigateway-limit-range
  namespace: apigateway
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container