apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notificationservice

namespace: notificationservice

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: notificationservice
  newTag: latest

commonLabels:
  app: notificationservice
  environment: production

patches:
- target:
    kind: Deployment
    name: notificationservice
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3