apiVersion: v1
kind: Namespace
metadata:
  name: webhookservice
  labels:
    name: webhookservice
    app: webhookservice
---
apiVersion: v1
kind: LimitRange
metadata:
  name: webhookservice-limit-range
  namespace: webhookservice
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container