routes:
  - prefix: "/api/auth"
    target: "auth-service:8010"
    methods: ["GET", "POST", "PUT", "DELETE"]
  
  - prefix: "/api/airtable"
    target: "airtable-gateway:8002" 
    methods: ["GET", "POST", "PUT", "DELETE"]
  
  - prefix: "/api/ai"
    target: "ai-processing-service:8001"
    methods: ["GET", "POST", "PUT", "DELETE"]